INTERFACE zif_animals_as
  PUBLIC .

METHODS : MAKE_SOUND
                       RETURNING VALUE(RESULT_SOUND)  TYPE STRING.

METHODS : EAT_FOOD
          RETURNING VALUE(RESULT_FOOD) TYPE STRING.

ENDINTERFACE.
